apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.authMigration.name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.authMigration.image | initials }}
          image: {{ .Values.authMigration.image }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgresql.auth.existingSecret }}
          command: ["migrate"]
          args: ["-verbose", "-path", "/db/migrations", "-database", "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ .Values.postgresql.hostname}}:{{ .Values.postgresql.primary.service.ports.postgresql}}/{{ .Values.auth.database}}?sslmode=disable&search_path=public", "up"]
      restartPolicy:  {{ .Values.authMigration.restartPolicy }}
  ttlSecondsAfterFinished: {{ .Values.authMigration.ttlSecondsAfterFinished }}
  backoffLimit: {{ .Values.authMigration.backoffLimit }}