apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.autoservice.name }}
  labels:
    app: {{ .Values.autoservice.name }}
spec:
  selector:
    app: {{ .Values.autoservice.name }} #the app label that service should listen to
  ports:
    - port: {{ .Values.autoservice.servicePort }} #the port that will be exposed by the service
      name: {{ .Values.web.name }}
      targetPort: {{.Values.app.name}}  #the port that service should listen to
  type: ClusterIP