app:
  name: homework-app
  baseHost: arch.homework
  migration:
    ttlSecondsAfterFinished: 10
    restartPolicy: Never
    backoffLimit: 4

  deployment:
    update:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

web:
  port: 8000
  name: http

autoservice:
  replicas: 2
  image: russbalabanov/msa_howmework:autoservice-v1.0.8
  migrations:
    name: autoservice-migration-job
    image: russbalabanov/msa_homework_migrations:autoservice-v1.0.8
  containerPort: 8081
  servicePort: 8082
  name: autoservice
  env: production

auth:
  containerPort: 8083
  servicePort: 8084
  name: auth-server
  replicas: 1
  servicePortName: auth-service-port
  portName: auth-web
  env: production
  database: auth
  image: russbalabanov/msa_howmework:auth-v1.0.11
  migrations:
    name: auth-migration-job
    image: russbalabanov/msa_homework_migrations:auth-v1.0.1

ingress-nginx:
  controller:
    extraArgs:
      v: 1
    service:
      ports:
        http: 2080
      enableHttps: false
      nodePorts:
        http: 32080

postgresql:
  hostname: msa-hw-chart-postgresql
  image:
    debug: true
  auth:
    database: app
    existingSecret: pg-secret
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD
  primary:
    initdb:
      scripts:
        init-pg.sql: |
          CREATE DATABASE auth;
    service:
      ports:
        postgresql: 5536
      type: LoadBalancer