app:
  name: homework-app
  baseHost: arch.homework
  deployment:
    update:
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0

web:
  port: 8000
  name: http

autoservice:
  replicas: 2
  image: russbalabanov/msa_howmework:autoservice-v1.0.6
  containerPort: 8081
  servicePort: 8082
  name: autoservice
  env: production

auth:
  containerPort: 8083
  servicePort: 8084
  name: auth-server
  replicas: 1
  servicePortName: auth-service-port
  portName: auth-web
  env: production
  database: auth
  image: russbalabanov/msa_howmework:auth-v1.0.10

migration:
  name: autoservice-migration-job
  image: russbalabanov/msa_homework_migrations:autoservice-v1.0.5
  ttlSecondsAfterFinished: 10
  restartPolicy: Never
  backoffLimit: 4

authMigration:
  name: auth-migration-job
  image: russbalabanov/msa_homework_migrations:auth-v1.0.1
  ttlSecondsAfterFinished: 10
  restartPolicy: Never
  backoffLimit: 4

nginx-ingress:
  controller:
    enableSnippets: true
    service:
      httpPort:
        port: 2080

postgresql:
  hostname: msa-hw-chart-postgresql
  image:
    debug: true
  auth:
    database: app
    existingSecret: pg-secret
    secretKeys:
      adminPasswordKey: POSTGRES_PASSWORD
      userPasswordKey: POSTGRES_PASSWORD
  primary:
    initdb:
      scripts:
        init-pg.sql: |
          CREATE DATABASE auth;
    service:
      ports:
        postgresql: 5536
      type: LoadBalancer